name: hotovson
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  shared_preferences: ^2.0.18 
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_emoji: "2.5.1"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  
